spring:
  application:
    name:
      ai-microservice
  docker:
    compose:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://www.mykeycloak.com:8040/auth/realms/recipe-app
          jwk-set-uri: "${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs"

server:
  port: 8473
  ssl:
    key-alias: "recipessl"
    key-password: "SSLkeystorePASS1"
    key-store: "classpath:recipessl.pfx"
    key-store-password: "SSLkeystorePASS1"
    trust-store: "classpath:recipessl.pfx"
    trust-store-password: "SSLkeystorePASS1"
    enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs.yaml
  swagger-ui:
    path: /swagger-ui/index.html